apiVersion: v1
kind: Pod
metadata:
  name: centos-pod
spec:
  serviceAccountName: jenkins
  containers:
  - name: uses-docker-image
    image: $DOCKER_IMAGE_NAME
    command: [ "echo", "SUCCESS" ]
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"